global:
  scrape_interval: 5s # Frecuencia alta para ver cambios rápidos en las pruebas de carga

scrape_configs:
  - job_name: 'backend_instances'
    static_configs:
      - targets: ['backend1:5000', 'backend2:5000', 'backend3:5000']